//! Bundled web tools served through the active web server (Nginx or Apache) +
//! PHP runtime. Currently just Adminer — a single-file database admin UI.

use tauri::{AppHandle, State};

use super::services::{self, ProcessRegistry};
use super::projects;
use crate::state::StateStore;

const ADMINER_URL: &str = "https://www.adminer.org/latest.php";
const ADMINER_DOMAIN: &str = "adminer.test";

/// Auto-login wrapper served as Adminer's `index.php`. Adminer refuses an empty
/// password on its login form, which collides with Stackr's passwordless loopback
/// root — so we skip the form and connect directly. PostgreSQL uses the `postgres`
/// superuser; MySQL/MariaDB use `root`. All are passwordless — loopback binding is
/// the security boundary. Switch engines via the URL (`?pgsql=127.0.0.1`).
// Note: Adminer resolves the hook via `function_exists('adminer_object')`, which
// checks the GLOBAL namespace — so this function must NOT be namespaced, even
// though the base class is `\Adminer\Adminer`. `login()` + `permanentLogin()`
// together lift Adminer's refusal of an empty password.
const ADMINER_AUTOLOGIN: &str = r#"<?php
function adminer_object() {
    class StackrAutoLogin extends \Adminer\Adminer {
        function credentials() {
            $user = (defined('Adminer\\DRIVER') && \Adminer\DRIVER === 'pgsql') ? 'postgres' : 'root';
            return ['127.0.0.1', $user, ''];
        }
        function login($login, $password) { return true; }
        function permanentLogin($create = false) { return 'stackr-local-dev'; }
    }
    return new StackrAutoLogin;
}

include './adminer.php';
"#;

/// Download Adminer if needed, serve it at `http://adminer.test` via the active
/// web server (Nginx or Apache) + PHP, register the host, and open it in the
/// browser. Adminer is just a PHP file, so it's web-server-agnostic — it's served
/// by whichever server is running, else whichever is installed.
#[tauri::command]
pub async fn open_adminer(
    app: AppHandle,
    state: State<'_, StateStore>,
    reg: State<'_, ProcessRegistry>,
) -> Result<(), String> {
    let (php_version, server_id) = {
        let st = state.0.lock().map_err(|e| e.to_string())?;
        let php = st
            .default_php
            .clone()
            .or_else(|| st.installed.iter().find(|c| c.component == "php").map(|c| c.version.clone()))
            .ok_or("Install PHP first (PHP tab).")?;
        // Same selection as projects: the running server, else Nginx, else
        // whichever web server is installed.
        let servers = projects::installed_web_servers(&st);
        let server_id = projects::resolve_active_server_id(&servers, &reg)
            .ok_or("Adminer is served through a web server — install Nginx or Apache first (Servers tab).")?;
        (php, server_id)
    };
    let server = server_id.split('-').next().unwrap_or("nginx").to_string();

    // Fetch Adminer once as `adminer.php`, and serve it through an auto-login
    // `index.php` wrapper (Adminer's own form rejects the empty password that
    // Stackr's passwordless loopback root uses).
    let dir = crate::paths::adminer_dir();
    let adminer = dir.join("adminer.php");
    if !adminer.exists() {
        crate::download::download_file(ADMINER_URL, &adminer).await?;
    }
    std::fs::write(dir.join("index.php"), ADMINER_AUTOLOGIN).map_err(|e| e.to_string())?;

    // Bring up PHP on its FastCGI port, write Adminer's vhost for the active
    // server, then start it (or reload if already up) so the vhost is applied.
    // The server's master config (which includes the vhosts) is regenerated by
    // spawn on a fresh start, or by reload_server when it's already running.
    let fcgi_port = services::ensure_php_runtime(&reg, &php_version)?;
    projects::write_vhost_file(&server, ADMINER_DOMAIN, &dir, fcgi_port, false)?;
    let spawned = services::ensure_started(&app, &reg, &server_id)?;
    if !spawned {
        services::reload_server(&app, &reg, &server_id)?;
    }

    let _ = crate::hosts::add_host(ADMINER_DOMAIN);
    projects::open_url(&format!("http://{ADMINER_DOMAIN}"));
    Ok(())
}

#[cfg(test)]
mod tests {
    /// Confirms the Adminer URL resolves to a real single-file PHP app.
    ///   cargo test downloads_adminer -- --ignored --nocapture
    #[tokio::test]
    #[ignore = "downloads adminer.php over the network"]
    async fn downloads_adminer() {
        let dest = std::env::temp_dir().join("stackr-adminer-test").join("index.php");
        let _ = std::fs::remove_file(&dest);
        crate::download::download_file(super::ADMINER_URL, &dest)
            .await
            .expect("download adminer");
        // Adminer's single file embeds binary (compressed) assets, so it isn't
        // valid UTF-8 as a whole — read raw bytes.
        let bytes = std::fs::read(&dest).expect("read adminer.php");
        assert!(bytes.starts_with(b"<?php"), "not a PHP file");
        assert!(
            bytes.windows(7).any(|w| w == b"Adminer"),
            "missing Adminer branding"
        );
        let _ = std::fs::remove_file(&dest);
    }
}
